title: Docs Católicos
description: Uma breve descrição do meu site.
baseurl: "/docscatolicos-novo"
url: "https://grupopadrepio1.github.io/docscatolicos-novo"  # Altere conforme necessário
theme: my-theme  # Nome do seu tema

locale: "pt-BR"  # Definindo o idioma para português do Brasil
